{
  "comments": [
    "Hello all.\n\nI get a \"cannot connect to vm\" error whenever I try to launch the eclipse debugger.\nHowever, I can run the program without any problem.\n\nHere is the error log :\n\njava.net.SocketException: Socket closed\nat java.net.PlainSocketImpl.socketAccept(Native Method)\nat java.net.PlainSocketImpl.accept(PlainSocketImpl.java:353)\nat java.net.ServerSocket.implAccept(ServerSocket.java:448)\nat java.net.ServerSocket.accept(ServerSocket.java:419)\nat org.eclipse.jdi.internal.connect.SocketTransportImpl.accept(SocketTransportImpl.java:87)\nat org.eclipse.jdi.internal.connect.SocketListeningConnectorImpl.accept(SocketListeningConnectorImpl.java:124)\nat org.eclipse.jdt.internal.launching.StandardVMDebugger$ConnectRunnable.run(StandardVMDebugger.java:78)\nat java.lang.Thread.run(Thread.java:552)\n\nand here is what the console says :\n\nError [22] in gethostbyname() call!\nerr:: Invalid argument\nSocket transport failed to init.\nTransport dt_socket failed to initialize, rc \u003d -1.\nFATAL ERROR in native method: No transports initialized\n\nIf anyone has an idea, I start desperating...\n\nClement",
    "Does the launch fail immediately or does it take a little time before it fails? What version of OSX are you running? Have you changed any of the default firewall settings? Which VM are you using (1.4 or 1.5)?",
    "The launch fails immediately, right after i click the debugger icon.\nI am using mac os X Tiger 10.4.3\nI left the default firewall settings (it\u0027s off).\nI am using the VM 1.4.2\n\nThanks for trying to help :-)\n\nClement",
    "Anything in your error log?\nHave you tried Eclipse 3.1?",
    "I showed my error log on the first message already.\nI haven\u0027t tried Eclipse 3.1 yet, i\u0027m running 3.0\nI guess i\u0027m gonna try that...",
    "I get the exact same error with Eclipse 3.1.1",
    "Sorry, stupid question. I was looking for another error that would indicate a boot classpath problem. If you get the same error on 3.1, that\u0027s not the issue.\n\nI suspect this is a firewall configuration issue. Clean installs of 3.0.x, 3.1.x and 3.2.x all work for me out of the box on 10.4.4.\n\nDoes running the following code work w/o exceptions?\n\npublic class Connect {\n    public static void main(String[] args) throws IOException {\n        Connect connect \u003d new Connect();\n        int port \u003d connect.startServer();\n        connect.startClient(port);\n    }\n\n    private void startClient(int port) throws IOException {\n        new Socket(\"localhost\", port);\n        System.out.println(\"Client connected\");\n    }\n\n    private int startServer() throws IOException {\n        final ServerSocket ss \u003d new ServerSocket(0);\n        int localPort \u003d ss.getLocalPort();\n        \n        new Thread(new Runnable() {\n            public void run() {\n                try {\n                    Socket socket \u003d ss.accept();\n                    InetAddress inetAddress \u003d socket.getInetAddress();\n                    System.out.println(\"Server accepted connection from: \" + inetAddress.getCanonicalHostName());\n                } catch (IOException e) {\n                    e.printStackTrace();\n                }\n            }\n        }).start();\n        \n        return localPort;\n    }\n}\n",
    "This code works fine w/o any exceptions.\nHere is the output :\n\nServer accepted connection from: localhost\nClient connected\n\nMay that come from mac OS 10.4 ?\n\nThanks",
    "Could be a problem with your host configuration. See bug #5163.\nYou could also try running the code in comment #6, but connect to \"127.0.0.1\" instead of \"localhost\"",
    "It worked !\nThanks Kevin, what I did is add the following entry in /etc/hosts :\nlocalhost       127.0.0.1\n\nGreat.",
    "Closing."
  ],
  "commentCreationDates": [
    "2006-01-23T03:20:16+01:00",
    "2006-01-23T15:01:40+01:00",
    "2006-01-23T17:50:47+01:00",
    "2006-01-23T17:57:04+01:00",
    "2006-01-23T18:01:43+01:00",
    "2006-01-23T18:15:46+01:00",
    "2006-01-23T18:29:58+01:00",
    "2006-01-23T18:45:59+01:00",
    "2006-01-24T17:31:59+01:00",
    "2006-01-25T14:15:49+01:00",
    "2006-01-26T21:18:45+01:00"
  ],
  "traces": [
    {
      "exceptionType": "java.net.SocketException",
      "message": "Socket closed",
      "elements": [
        {
          "method": "java.net.PlainSocketImpl.socketAccept",
          "source": "Native Method"
        },
        {
          "method": "java.net.PlainSocketImpl.accept",
          "source": "PlainSocketImpl.java:353"
        },
        {
          "method": "java.net.ServerSocket.implAccept",
          "source": "ServerSocket.java:448"
        },
        {
          "method": "java.net.ServerSocket.accept",
          "source": "ServerSocket.java:419"
        },
        {
          "method": "org.eclipse.jdi.internal.connect.SocketTransportImpl.accept",
          "source": "SocketTransportImpl.java:87"
        },
        {
          "method": "org.eclipse.jdi.internal.connect.SocketListeningConnectorImpl.accept",
          "source": "SocketListeningConnectorImpl.java:124"
        },
        {
          "method": "org.eclipse.jdt.internal.launching.StandardVMDebugger$ConnectRunnable.run",
          "source": "StandardVMDebugger.java:78"
        },
        {
          "method": "java.lang.Thread.run",
          "source": "Thread.java:552"
        }
      ],
      "number": 0,
      "commentIndex": 0,
      "bugId": "124814",
      "date": "2006-01-23T03:20:16+01:00",
      "product": "Platform",
      "component": "Debug",
      "severity": "normal"
    }
  ],
  "groupId": "124814",
  "bugId": "124814",
  "date": "2006-01-23T03:20:16+01:00",
  "product": "Platform",
  "component": "Debug",
  "severity": "normal"
}