{
  "comments": [
    "-Run debug session.\n-While session is being run, close eclipse.\n*** THe following exception appears in the shell:\n\n\nException in thread \"Thread-127\" java.lang.NullPointerException\n        at \norg.eclipse.php.debug.core.PHPDebugPlugin.log(PHPDebugPlugin.java:143)\n        at \norg.eclipse.php.debug.core.PHPDebugPlugin.log(PHPDebugPlugin.java:147)\n        at \norg.eclipse.php.debug.core.communication.DebugConnectionThread$InputMessageHandler.run(DebugConnectionThread.java:741)\n        at java.lang.Thread.run(Unknown Source)",
    "Doesn\u0027t happen",
    "still exists",
    "Fixed.",
    "Fixed"
  ],
  "commentCreationDates": [
    "2006-06-26T15:21:43+02:00",
    "2006-08-21T17:18:58+02:00",
    "2006-09-10T12:11:21+02:00",
    "2006-09-11T09:20:40+02:00",
    "2006-09-20T14:15:28+02:00"
  ],
  "traces": [
    {
      "exceptionType": "java.lang.NullPointerException",
      "elements": [
        {
          "method": "org.eclipse.php.debug.core.PHPDebugPlugin.log",
          "source": "PHPDebugPlugin.java:143"
        },
        {
          "method": "org.eclipse.php.debug.core.PHPDebugPlugin.log",
          "source": "PHPDebugPlugin.java:147"
        },
        {
          "method": "org.eclipse.php.debug.core.communication.DebugConnectionThread$InputMessageHandler.run",
          "source": "DebugConnectionThread.java:741"
        },
        {
          "method": "java.lang.Thread.run",
          "source": "Unknown Source"
        }
      ],
      "number": 0,
      "commentIndex": 0,
      "bugId": "148643",
      "date": "2006-06-26T15:21:43+02:00",
      "product": "PDT",
      "component": "Debug-core",
      "severity": "normal"
    }
  ],
  "groupId": "148643",
  "bugId": "148643",
  "date": "2006-06-26T15:21:43+02:00",
  "product": "PDT",
  "component": "Debug-core",
  "severity": "normal"
}