{
  "comments": [
    "build I20040225\n\n- was stepping through some tests\n- they succeeded, so I resumed and the workbench under test exited\n- got the following while it was shutting down\n\norg.eclipse.core.internal.runtime.AssertionFailedException: assertion failed: \nThe application has not been initialized.\n\tat org.eclipse.core.internal.runtime.Assert.isTrue(Assert.java:101)\n\tat org.eclipse.core.internal.runtime.InternalPlatform.assertInitialized\n(InternalPlatform.java:242)\n\tat org.eclipse.core.internal.runtime.InternalPlatform.log\n(InternalPlatform.java:620)\n\tat org.eclipse.core.internal.runtime.InternalPlatform.handleException\n(InternalPlatform.java:375)\n\tat org.eclipse.core.internal.runtime.InternalPlatform.run\n(InternalPlatform.java:790)\n\tat org.eclipse.core.internal.jobs.JobListeners.doNotify\n(JobListeners.java:87)\n\tat org.eclipse.core.internal.jobs.JobListeners.done\n(JobListeners.java:136)\n\tat org.eclipse.core.internal.jobs.JobManager.endJob(JobManager.java:372)\n\tat org.eclipse.core.internal.jobs.WorkerPool.endJob(WorkerPool.java:119)\n\tat org.eclipse.core.internal.jobs.Worker.run(Worker.java:72)",
    "This appeared in the debug console.\nNothing of interest was in either my host\u0027s log or the runtime test workspace\u0027s.\n",
    "It is failing to write to the log since the platform is no longer running. The\nsafe runnable mechanism should not throw exceptions, so I will change it to only\nwrite to the log if the platform is running. If the platform is not running, it\nwill write the exception on stderr.  In this situation, the exception that was\nbeing logged got lost due to the exception attempting to write to the log file.",
    "Fix released"
  ],
  "commentCreationDates": [
    "2004-02-27T03:42:46+01:00",
    "2004-02-27T03:45:23+01:00",
    "2004-03-04T17:50:37+01:00",
    "2004-03-05T16:55:07+01:00"
  ],
  "traces": [
    {
      "exceptionType": "org.eclipse.core.internal.runtime.AssertionFailedException",
      "message": "assertion failed:  The application has not been initialized.",
      "elements": [
        {
          "method": "org.eclipse.core.internal.runtime.Assert.isTrue",
          "source": "Assert.java:101"
        },
        {
          "method": "org.eclipse.core.internal.runtime.InternalPlatform.assertInitialized",
          "source": "InternalPlatform.java:242"
        },
        {
          "method": "org.eclipse.core.internal.runtime.InternalPlatform.log",
          "source": "InternalPlatform.java:620"
        },
        {
          "method": "org.eclipse.core.internal.runtime.InternalPlatform.handleException",
          "source": "InternalPlatform.java:375"
        },
        {
          "method": "org.eclipse.core.internal.runtime.InternalPlatform.run",
          "source": "InternalPlatform.java:790"
        },
        {
          "method": "org.eclipse.core.internal.jobs.JobListeners.doNotify",
          "source": "JobListeners.java:87"
        },
        {
          "method": "org.eclipse.core.internal.jobs.JobListeners.done",
          "source": "JobListeners.java:136"
        },
        {
          "method": "org.eclipse.core.internal.jobs.JobManager.endJob",
          "source": "JobManager.java:372"
        },
        {
          "method": "org.eclipse.core.internal.jobs.WorkerPool.endJob",
          "source": "WorkerPool.java:119"
        },
        {
          "method": "org.eclipse.core.internal.jobs.Worker.run",
          "source": "Worker.java:72"
        }
      ],
      "number": 0,
      "commentIndex": 0,
      "bugId": "53248",
      "date": "2004-02-27T03:42:46+01:00",
      "product": "Platform",
      "component": "Resources",
      "severity": "normal"
    }
  ],
  "groupId": "53248",
  "bugId": "53248",
  "date": "2004-02-27T03:42:46+01:00",
  "product": "Platform",
  "component": "Resources",
  "severity": "normal"
}