{
  "comments": [
    "I\u0027m using 3.1 M5a.\n\nThe target platform for my workspace is 2.1.3.\n\nI have a subclass of junit.framework.TestCase. When I try to run this test \nas \"Junit plugin test\", I get an exception in the \nlog : \"IllegalArgumentException: Application not found: \norg.eclipse.pde.junit.runtime.legacyCoretestapplication. at \norg.eclipse.core.internal.boot.InternalBootLoader.run\n(InternalBootLoader.java:856)\"",
    "I forgot to mention, but the same test is correctly run under 3.1 M4.",
    "\n\n*** This bug has been marked as a duplicate of 86301 ***"
  ],
  "commentCreationDates": [
    "2005-02-24T10:21:03+01:00",
    "2005-02-24T11:46:48+01:00",
    "2005-02-28T03:29:21+01:00"
  ],
  "traces": [
    {
      "exceptionType": "IllegalArgumentException",
      "message": "Application not found:  org.eclipse.pde.junit.runtime.legacyCoretestapplication.",
      "elements": [
        {
          "method": "org.eclipse.core.internal.boot.InternalBootLoader.run",
          "source": "InternalBootLoader.java:856"
        }
      ],
      "number": 0,
      "commentIndex": 0,
      "bugId": "86449",
      "duplicateId": "86301",
      "date": "2005-02-24T10:21:03+01:00",
      "product": "PDE",
      "component": "UI",
      "severity": "normal"
    }
  ],
  "groupId": "86301",
  "bugId": "86449",
  "duplicateId": "86301",
  "date": "2005-02-24T10:21:03+01:00",
  "product": "PDE",
  "component": "UI",
  "severity": "normal"
}