{
  "comments": [
    "A RemoteInvocationException is intermmitenly received from the \nTestExecutionHarness. The root cause of this exception is an \nInactiveAgentException in the AgentImpl class (see StackTrace) that occurs in \nthe AgentImpl:connectionClosed() method. This seems to be caused due to the \nConnectionImpl:SocketReaderThread which ends up calling the disconnect() method \nwhen an end-of-file is received from the Socket Read. Normally the EOF is not \nreached however whenever there is an EOF then the next test that is launched \ngets the RemoteInvocationException due to the above code path and only restart \nof the workbench clears the cached state in the TestExecutionHarness.\n\nIn Hyades 3.0.2 this exception is also caught and a getMessage() is invoked on \nthe Exception returning a null since the RemoteInvocationException does not \nhave a message.\n\nSo the scenario above ends with \"null\" in the StringBuffer returned by the \nlaunch() method of the TestExecutionHarness and data cached in the TEH that can \nonly be cleared by restarting the Workbench. All this results in one unhappy \ncamper.\n\n\norg.eclipse.hyades.execution.invocation.RemoteInvocationException\n\tat org.eclipse.hyades.execution.local.SessionImpl.invokeRemote(Unknown \nSource)\n\tat org.eclipse.hyades.execution.local.SessionStub.invokeRemote(Unknown \nSource)\n\tat \norg.eclipse.hyades.execution.local.ExecutionComponentFactoryImpl.delegateRemoteC\nall(Unknown Source)\n\tat \norg.eclipse.hyades.execution.local.EclipseExecutionComponentFactoryImpl.addExecu\ntionComponent(Unknown Source)\n\tat \norg.eclipse.hyades.execution.harness.TestExecutionHarness.initializeRegisteredEx\necutionComponents(Unknown Source)\n\tat org.eclipse.hyades.execution.harness.TestExecutionHarness.launchTest\n(Unknown Source)\n\tat org.eclipse.hyades.execution.harness.TestExecutionHarness.launchTest\n(Unknown Source)\n\tat org.eclipse.hyades.execution.harness.TestExecutionHarness.launchTest\n(Unknown Source)",
    "This problem (as detailed below) seems to originate from the AgentController \nJVM going away. The servicelog.log of the AgentController identifies a severe \nerror as the cause:\n\n\u003cSERVER_MSG time\u003d\"2005:3:4:12:18:34\" severity\u003d\"WARNING\" text\u003d\"Registered Agent \nUUID-1109956714-725767-1539138514-229685412.\"/\u003e\n\u003cSERVER_MSG time\u003d\"2005:3:4:12:18:36\" severity\u003d\"INFORMATION\" text\u003d\"Preparing \nAgent active\"/\u003e\n\u003cSERVER_MSG time\u003d\"2005:3:4:12:18:36\" severity\u003d\"WARNING\" text\u003d\"Requesting shared \nmemory 1048576 bytes, allocating 1048576 bytes, system max 33554432 bytes\"/\u003e\n\u003cSERVER_MSG time\u003d\"2005:3:4:12:18:36\" severity\u003d\"INFORMATION\" text\u003d\"Created data \nchannel with name rabuffer1 and CB addr 0xae526154 buffer addr 0xae5272ec size \nin\u003d1048576 size out\u003d1048576\"/\u003e\n\u003cSERVER_MSG time\u003d\"2005:3:4:12:18:36\" severity\u003d\"INFORMATION\" text\u003d\"Connected to \nclient data channel socket on port 4432 with descriptor 51\"/\u003e\n\u003cSERVER_MSG time\u003d\"2005:3:4:12:18:36\" severity\u003d\"INFORMATION\" text\u003d\"Created \nflusher thread and about to send message to agent\"/\u003e\n\u003cSERVER_MSG time\u003d\"2005:3:4:12:19:54\" severity\u003d\"INFORMATION\" text\u003d\"Process 8268 \ndoes not exist so scrub it\"/\u003e\n\u003cSERVER_MSG time\u003d\"2005:3:4:12:19:54\" severity\u003d\"INFORMATION\" text\u003d\"Process 8268 \nexited\"/\u003e\n\u003cSERVER_MSG time\u003d\"2005:3:4:12:19:54\" severity\u003d\"WARNING\" text\u003d\"Client connection \nrequest failed with platform specific error 22 (Invalid argument)\"/\u003e\n\u003cSERVER_MSG time\u003d\"2005:3:4:12:19:54\" severity\u003d\"SEVERE\" text\u003d\"Client connection \nrequest failed with platform specific error 9 (Bad file descriptor)\"/\u003e\n\n",
    "\nThere was a defect fix to 3.3 that enhanced the test execution harness session \ncache feature--this defect was bugzilla_79438.  \n\nI am not aware of what is causing bad things to happen as described below, but \nonce bad things happen, recovery is likely possible for the next test by \napplying the fix for bugzilla_79438 in the 3.0.2 if it is possible.",
    "\nThe session cache fix that was put in after 3.0.2 seems to fix things so that \ntests are still run in cases where the agents do not seem to reset gracefully \n(the problems that Javier found).  I will run a report to see what changed and \nis ultimately causing the RemoteInvocationException to occur in the first \nplace.",
    "\nI cannot close this defect yet since we don\u0027t have a delivery vehicle to get \nthe fix into or around 3.0.2 currently.",
    "\n...",
    "\nThis has been fixed in 3.3 and later -- the submitter has a workaround to \nclear the cache at given times outside of the TPTP code (from the downstream \nproduct using TPTP).  Closing out per test call on 4/25/2005."
  ],
  "commentCreationDates": [
    "2005-03-04T16:14:48+01:00",
    "2005-03-05T23:07:13+01:00",
    "2005-03-07T16:24:58+01:00",
    "2005-03-09T15:54:18+01:00",
    "2005-03-09T15:58:17+01:00",
    "2005-03-09T15:58:33+01:00",
    "2005-04-25T17:37:49+02:00"
  ],
  "traces": [
    {
      "exceptionType": "org.eclipse.hyades.execution.invocation.RemoteInvocationException",
      "elements": [
        {
          "method": "org.eclipse.hyades.execution.local.SessionImpl.invokeRemote",
          "source": "Unknown  Source"
        },
        {
          "method": "org.eclipse.hyades.execution.local.SessionStub.invokeRemote",
          "source": "Unknown  Source"
        },
        {
          "method": "org.eclipse.hyades.execution.local.ExecutionComponentFactoryImpl.delegateRemoteCall",
          "source": "Unknown Source"
        },
        {
          "method": "org.eclipse.hyades.execution.local.EclipseExecutionComponentFactoryImpl.addExecutionComponent",
          "source": "Unknown Source"
        },
        {
          "method": "org.eclipse.hyades.execution.harness.TestExecutionHarness.initializeRegisteredExecutionComponents",
          "source": "Unknown Source"
        },
        {
          "method": "org.eclipse.hyades.execution.harness.TestExecutionHarness.launchTest",
          "source": "Unknown Source"
        },
        {
          "method": "org.eclipse.hyades.execution.harness.TestExecutionHarness.launchTest",
          "source": "Unknown Source"
        },
        {
          "method": "org.eclipse.hyades.execution.harness.TestExecutionHarness.launchTest",
          "source": "Unknown Source"
        }
      ],
      "number": 0,
      "commentIndex": 0,
      "bugId": "87155",
      "date": "2005-03-04T16:14:48+01:00",
      "product": "Hyades",
      "component": "Exec.harness",
      "severity": "critical"
    }
  ],
  "groupId": "87155",
  "bugId": "87155",
  "date": "2005-03-04T16:14:48+01:00",
  "product": "Hyades",
  "component": "Exec.harness",
  "severity": "critical"
}